-- migrations/015_create_user_financial_targets_table.sql

-- 1. Create enum types for structured data
CREATE TYPE public.financial_target_type AS ENUM ('currency', 'percentage');
CREATE TYPE public.financial_timescale AS ENUM ('monthly', 'yearly');

-- 2. Create the table
CREATE TABLE public.user_financial_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id INTEGER REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    metric_name TEXT NOT NULL,
    target_value DECIMAL NOT NULL,
    target_type public.financial_target_type NOT NULL,
    timescale public.financial_timescale NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(profile_id, metric_name)
);

-- 3. Enable RLS
ALTER TABLE public.user_financial_targets ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
CREATE POLICY "Users can view their own financial targets"
ON public.user_financial_targets
FOR SELECT USING ( profile_id = (SELECT id FROM public.profiles WHERE email = auth.email()) );

CREATE POLICY "Users can insert their own financial targets"
ON public.user_financial_targets
FOR INSERT WITH CHECK ( profile_id = (SELECT id FROM public.profiles WHERE email = auth.email()) );

CREATE POLICY "Users can update their own financial targets"
ON public.user_financial_targets
FOR UPDATE USING ( profile_id = (SELECT id FROM public.profiles WHERE email = auth.email()) )
WITH CHECK ( profile_id = (SELECT id FROM public.profiles WHERE email = auth.email()) );

CREATE POLICY "Users can delete their own financial targets"
ON public.user_financial_targets
FOR DELETE USING ( profile_id = (SELECT id FROM public.profiles WHERE email = auth.email()) );

-- 5. Add updated_at trigger
-- Reuses the function created in migration 001
CREATE TRIGGER update_user_financial_targets_updated_at_trigger
BEFORE UPDATE ON public.user_financial_targets
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
