
-- Tabela de seguidores
CREATE TABLE IF NOT EXISTS followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    following_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT followers_unique UNIQUE (follower_id, following_id)
);

-- Habilitar RLS se não estiver habilitado
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_class
        WHERE relname = 'followers'
          AND relrowsecurity = true
    ) THEN
        ALTER TABLE followers ENABLE ROW LEVEL SECURITY;
    END IF;
END $$;

-- Policies para a tabela de seguidores

-- Usuários podem seguir outros usuários (INSERT)
DROP POLICY IF EXISTS "user_can_follow_other_users" ON followers;
CREATE POLICY "user_can_follow_other_users"
ON followers
FOR INSERT
WITH CHECK (auth.uid() = follower_id);

-- Usuários podem deixar de seguir outros usuários (DELETE)
DROP POLICY IF EXISTS "user_can_unfollow_other_users" ON followers;
CREATE POLICY "user_can_unfollow_other_users"
ON followers
FOR DELETE
USING (auth.uid() = follower_id);

-- Todos podem ver as relações de seguidores (SELECT)
DROP POLICY IF EXISTS "all_users_can_see_follower_relationships" ON followers;
CREATE POLICY "all_users_can_see_follower_relationships"
ON followers
FOR SELECT
USING (true);
